export const textColorPrimary = () => 'black'
export const textColorSecondary = () => 'white'
export const textColorHeader = () => 'red'
export const navBarColorSelected = () => 'orange'
export const navBarColorNotSelected = () => 'white'
export const iconsColorPrimary = () => 'white'
export const activityColorPrimary = () => 'red'
export const progressBarColor = () => 'red'